package org.safari.et.model;
// Generated Apr 4, 2022 3:18:13 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,schema="public"
)
public class User  implements java.io.Serializable {


     private long id;
     private String firstname;
     private String lastname;

    public User() {
    }

    public User(long id, String firstname, String lastname) {
       this.id = id;
       this.firstname = firstname;
       this.lastname = lastname;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="firstname", nullable=false)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname", nullable=false)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }




}


