package org.safari.et.model;
// Generated Apr 4, 2022 3:18:13 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Values generated by hbm2java
 */
@Entity
@Table(name="values"
    ,schema="public"
)
public class Values  implements java.io.Serializable {


     private long id;
     private int numbera;
     private int numberb;

    public Values() {
    }

    public Values(long id, int numbera, int numberb) {
       this.id = id;
       this.numbera = numbera;
       this.numberb = numberb;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="numbera", nullable=false)
    public int getNumbera() {
        return this.numbera;
    }
    
    public void setNumbera(int numbera) {
        this.numbera = numbera;
    }

    
    @Column(name="numberb", nullable=false)
    public int getNumberb() {
        return this.numberb;
    }
    
    public void setNumberb(int numberb) {
        this.numberb = numberb;
    }




}


